IIB:
  image: ibmcom/iib:${IIB_VERSION}
  environment:
    - LANG
    - LICENSE
    - NODENAME=${IIB_NODE_NAME}
    - SERVERNAME=${IIB_SERVER_NAME}
  ports:
    - 7800:7800
    - 4414:4414

MQ:
  image: ibmcom/mq:8
  environment:
    - LANG
    - LICENSE
    - MQ_QMGR_NAME=${MQ_QMGR_NAME}
    - LOG_FORMAT=json
  ports:
    - 1414:1414

