#!/bin/bash

if [ -z "$IIB_SRC_DIR_PATH" ]; then
	echo "env IIB_SRC_DIR_PATH missing"

	exit 1
fi

if [ -z "$IIB_VERSION" ]; then
	echo "env IIB_VERSION missing"

	exit 1
fi

if [ -z "$MQSI_VERSION" ]; then
	source "$IIB_SRC_DIR_PATH/iib-$IIB_VERSION/server/bin/mqsiprofile"
fi
