#!/bin/bash
# © Copyright IBM Corporation 2015.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

set -e

iib-create-node() {
	echo "Node $IIB_NODE_NAME does not exist..."
	echo "Creating node $IIB_NODE_NAME"
	mqsicreatebroker $IIB_NODE_NAME
}

iib-is-node-running() {
	mqsilist | grep $IIB_NODE_NAME | grep -q -e "running"
}

iib-start-node() {
	if ! iib-is-node-running; then
		echo "Starting node $IIB_NODE_NAME"
		mqsistart $IIB_NODE_NAME
	fi
}

iib-is-node-exist() {
	mqsilist | grep -q -e $IIB_NODE_NAME
}

iib-create-integration-server() {
	echo "Creating integration server $IIB_SERVER_NAME"
	mqsicreateexecutiongroup $IIB_NODE_NAME -e $IIB_SERVER_NAME -w 120
}

start() {
	iib version

	if ! iib-is-node-exist; then
		iib-create-node
	fi

	iib-create-integration-server
	iib-start-node
}

stop() {
	echo "Stopping node $IIB_NODE_NAME..."
	mqsistop $IIB_NODE_NAME
}

monitor() {
	echo "Running - stop container to exit"
	# Loop forever by default - container must be stopped manually.
	# Here is where you can add in conditions controlling when your container will exit - e.g. check for existence of specific processes stopping or errors beiing reported
	while true; do
		sleep 1
	done
}

iib-license-check
source $(which iib-configure-env)

start
trap stop SIGTERM SIGINT
monitor
